@Gateway = http://localhost:8080

# Solicitudes para Gateway ejecutado mediante Docker Compose.
GET {{Gateway}}/
Accept: application/json

###

GET {{Gateway}}/weather?days=5
Accept: application/json

###

GET {{Gateway}}/health
Accept: application/json
