@WeatherApi = http://localhost:8081

# Solicitudes para Weather ejecutado mediante Docker Compose.
GET {{WeatherApi}}/
Accept: application/json

###

GET {{WeatherApi}}/health
Accept: application/json
